# Generated by Django 5.2.7 on 2025-10-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-status', 'title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
