# Generated by Django 5.2.7 on 2025-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracking', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
